vich_uploader:
    db_driver: orm
    mappings:
        contact_profile_images:
            uri_prefix: /uploads/contacts
            upload_destination: '%kernel.project_dir%/public/uploads/contacts'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
