<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJRFI5Xd\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJRFI5Xd/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerJRFI5Xd.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerJRFI5Xd\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerJRFI5Xd\App_KernelProdDebugContainer([
    'container.build_hash' => 'JRFI5Xd',
    'container.build_id' => 'dbb55123',
    'container.build_time' => 1754944715,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJRFI5Xd');
