<?php

namespace ContainerCk9gaIf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BIstAG_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bIstAG.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bIstAG.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ContactController::createContact' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\ContactController::createContact()', 'getContactControllercreateContactService', true],
            'App\\Controller\\ContactController::getMyContacts' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::getMyContacts()', 'getContactControllergetMyContactsService', true],
            'App\\Controller\\ContactController::getContact' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::getContact()', 'getContactControllergetContactService', true],
            'App\\Controller\\ContactController::updateContact' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\ContactController::updateContact()', 'getContactControllerupdateContactService', true],
            'App\\Controller\\ContactController::deleteContact' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::deleteContact()', 'getContactControllerdeleteContactService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.JupvnRz.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.o6K9g7o.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ContactController:createContact' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\ContactController::createContact()', 'getContactControllercreateContactService', true],
            'App\\Controller\\ContactController:getMyContacts' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::getMyContacts()', 'getContactControllergetMyContactsService', true],
            'App\\Controller\\ContactController:getContact' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::getContact()', 'getContactControllergetContactService', true],
            'App\\Controller\\ContactController:updateContact' => ['privates', '.service_locator.AJ5eq3c.App\\Controller\\ContactController::updateContact()', 'getContactControllerupdateContactService', true],
            'App\\Controller\\ContactController:deleteContact' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\ContactController::deleteContact()', 'getContactControllerdeleteContactService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.JupvnRz.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.o6K9g7o.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ContactController::createContact' => '?',
            'App\\Controller\\ContactController::getMyContacts' => '?',
            'App\\Controller\\ContactController::getContact' => '?',
            'App\\Controller\\ContactController::updateContact' => '?',
            'App\\Controller\\ContactController::deleteContact' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Controller\\UserController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ContactController:createContact' => '?',
            'App\\Controller\\ContactController:getMyContacts' => '?',
            'App\\Controller\\ContactController:getContact' => '?',
            'App\\Controller\\ContactController:updateContact' => '?',
            'App\\Controller\\ContactController:deleteContact' => '?',
            'App\\Controller\\UserController:register' => '?',
            'App\\Controller\\UserController:login' => '?',
        ]);
    }
}
