<?php

namespace ContainerCk9gaIf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllercreateContactService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJ5eq3c.App\Controller\ContactController::createContact()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AJ5eq3c'] ?? $container->load('get_ServiceLocator_AJ5eq3cService'));

        if (isset($container->privates['.service_locator.AJ5eq3c.App\\Controller\\ContactController::createContact()'])) {
            return $container->privates['.service_locator.AJ5eq3c.App\\Controller\\ContactController::createContact()'];
        }

        return $container->privates['.service_locator.AJ5eq3c.App\\Controller\\ContactController::createContact()'] = $a->withContext('App\\Controller\\ContactController::createContact()', $container);
    }
}
