<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \App\Entity\Contact implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null, 16],
        "\0".parent::class."\0".'owner' => [parent::class, 'owner', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'profileImage' => [parent::class, 'profileImage', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'note' => [parent::class, 'note', null, 16],
        'owner' => [parent::class, 'owner', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'profileImage' => [parent::class, 'profileImage', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
